### ISSUE TITLE
Race condition after registering for first time

### ISSUE THREAD

**Issue by orsondmc** [team-catgirl/collar#33]
There is a race condition in the new device registration code that signals to the client with `StartSessionResponse ` BEFORE keys are correctly setup. I suspect this may be a MongoDB consistency issue but we should also look at the order of the packet request/responses before sending `StartSessionResponse`

```
java.lang.IllegalArgumentException: Empty key
	at java.base/javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
	at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
	at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
	at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
	at team.catgirl.collar.security.signal.SignalCypher.crypt(SignalCypher.java:32)
	at team.catgirl.collar.protocol.PacketIO.encodeEncrypted(PacketIO.java:71)
	at team.catgirl.collar.client.Collar$CollarWebSocket.sendRequest(Collar.java:347)
	at team.catgirl.collar.client.Collar$CollarWebSocket.lambda$onOpen$0(Collar.java:210)
	at team.catgirl.collar.client.Collar.lambda$new$1(Collar.java:73)
	at team.catgirl.collar.client.api.groups.GroupsApi.create(GroupsApi.java:63)
	at team.catgirl.collar.tests.groups.GroupsTest.createGroup(GroupsTest.java:50)
```

**Comment by orsondmc** [comment]
Fixed on topic/groups-test
