### ISSUE TITLE
org.whispersystems.libsignal.InvalidMessageException: Over 2000 messages into the future!

### ISSUE THREAD

**Issue by orsondmc** [team-catgirl/collar#88]
```
2021-03-18T10:33:12.821705+00:00 app[web.1]: SEVERE: Unrecoverable error Problem decrypting message from 4314b415-4eaf-4b9e-b16a-e505cb656985:1
2021-03-18T10:33:12.821706+00:00 app[web.1]: java.lang.IllegalStateException: Problem decrypting message from 4314b415-4eaf-4b9e-b16a-e505cb656985:1
2021-03-18T10:33:12.821706+00:00 app[web.1]: 	at team.catgirl.collar.security.signal.AbstractCipher.decrypt(AbstractCipher.java:102)
2021-03-18T10:33:12.821707+00:00 app[web.1]: 	at team.catgirl.collar.protocol.PacketIO.decode(PacketIO.java:47)
2021-03-18T10:33:12.821707+00:00 app[web.1]: 	at team.catgirl.collar.protocol.PacketIO.decode(PacketIO.java:31)
2021-03-18T10:33:12.821708+00:00 app[web.1]: 	at team.catgirl.collar.server.CollarServer.read(CollarServer.java:204)
2021-03-18T10:33:12.821708+00:00 app[web.1]: 	at team.catgirl.collar.server.CollarServer.processMessage(CollarServer.java:109)
2021-03-18T10:33:12.821708+00:00 app[web.1]: 	at team.catgirl.collar.server.CollarServer.message(CollarServer.java:102)
2021-03-18T10:33:12.821709+00:00 app[web.1]: 	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
2021-03-18T10:33:12.821709+00:00 app[web.1]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-18T10:33:12.821710+00:00 app[web.1]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2021-03-18T10:33:12.821710+00:00 app[web.1]: 	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
2021-03-18T10:33:12.821715+00:00 app[web.1]: 	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
2021-03-18T10:33:12.821715+00:00 app[web.1]: 	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onBinaryFrame$0(JettyAnnotatedEventDriver.java:106)
2021-03-18T10:33:12.821716+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
2021-03-18T10:33:12.821716+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
2021-03-18T10:33:12.821716+00:00 app[web.1]: 	at java.base/java.lang.Thread.run(Thread.java:832)
2021-03-18T10:33:12.821717+00:00 app[web.1]: Caused by: org.whispersystems.libsignal.InvalidMessageException: No valid sessions.
2021-03-18T10:33:12.821717+00:00 app[web.1]: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:290)
2021-03-18T10:33:12.821717+00:00 app[web.1]: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:243)
2021-03-18T10:33:12.821718+00:00 app[web.1]: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:211)
2021-03-18T10:33:12.821718+00:00 app[web.1]: 	at team.catgirl.collar.security.signal.AbstractCipher.decrypt(AbstractCipher.java:73)
2021-03-18T10:33:12.821719+00:00 app[web.1]: 	... 14 more
2021-03-18T10:33:12.821719+00:00 app[web.1]: Caused by: org.whispersystems.libsignal.InvalidMessageException: Over 2000 messages into the future!
2021-03-18T10:33:12.821720+00:00 app[web.1]: 	at org.whispersystems.libsignal.SessionCipher.getOrCreateMessageKeys(SessionCipher.java:382)
2021-03-18T10:33:12.821720+00:00 app[web.1]: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:310)
2021-03-18T10:33:12.821721+00:00 app[web.1]: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:268)
2021-03-18T10:33:12.821721+00:00 app[web.1]: 	... 17 more
2021-03-18T10:33:12.821721+00:00 app[web.1]: 
```

**Comment by orsondmc** [comment]
I think this happens because we do not guard the /collar connect command correctly and two instances of a running `Collar` client are created.
